# Generated by Django 3.1 on 2020-08-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20200818_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ffnId',
            new_name='playerId',
        ),
    ]
