# Generated by Django 3.1 on 2020-08-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20200818_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ranking',
            new_name='pprRanking',
        ),
        migrations.AddField(
            model_name='player',
            name='standardRanking',
            field=models.IntegerField(default=999),
        ),
    ]
