# Generated by Django 3.1 on 2020-09-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20200902_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='roster',
        ),
        migrations.AddField(
            model_name='roster',
            name='players',
            field=models.ManyToManyField(blank=True, to='players.Player'),
        ),
    ]
