# Generated by Django 3.1 on 2020-09-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_roster_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
